using Dapper;
using DataStorage.Models;
using FirebirdSql.Data.FirebirdClient;
using System.Data;

namespace DataStorage {

    /// <summary>
    /// Sharded data storage for ASCOM ObservingConditions and SafetyMonitor data
    /// </summary>
    public class DataStorage {

        #region Private Fields

        private const string DatabaseFileExtension = ".fdb";
        private const string TableName = "METEO_DATA";
        private readonly string _password;
        private readonly string _storageRootPath;
        private readonly string _userName;

        #endregion Private Fields

        #region Public Constructors

        /// <summary>
        /// Initialize sharded data storage
        /// </summary>
        /// <param name="storageRootPath">Root directory for storing database shards</param>
        /// <param name="userName">FireBird user name (default: SYSDBA)</param>
        /// <param name="password">FireBird password (default: masterkey)</param>
        public DataStorage(string storageRootPath, string? userName = null, string? password = null) {
            if (string.IsNullOrWhiteSpace(storageRootPath)) {
                throw new ArgumentException("Storage root path cannot be null or empty", nameof(storageRootPath));
            }

            _storageRootPath = storageRootPath;
            _userName = string.IsNullOrWhiteSpace(userName) ? "SYSDBA" : userName;
            _password = string.IsNullOrWhiteSpace(password) ? "masterkey" : password;

            // Ensure root directory exists
            if (!Directory.Exists(_storageRootPath)) {
                Directory.CreateDirectory(_storageRootPath);
            }
        }

        #endregion Public Constructors

        #region Public Methods

        /// <summary>
        /// Add observing data to storage
        /// </summary>
        /// <param name="data">Data to store</param>
        public void AddData(ObservingData data) {
            ArgumentNullException.ThrowIfNull(data);

            var dbPath = GetDatabasePath(data.Timestamp);
            EnsureDatabaseExists(dbPath);

            using var connection = new FbConnection(GetConnectionString(dbPath));
            connection.Open();

            // ID will be auto-generated by database
            data.Id = 0;

            // Create SQL INSERT statement
            var sql = @"INSERT INTO METEO_DATA (
                            CREATED_AT,     CLOUD_COVER,    DEW_POINT,          HUMIDITY,   PRESSURE,       RAIN_RATE, 
                            SKY_BRIGHTNESS, SKY_QUALITY,    SKY_TEMPERATURE,    STAR_FWHM,  TEMPERATURE,    WIND_DIRECTION, 
                            WIND_GUST,      WIND_SPEED,     IS_SAFE,            NOTES) 
                        VALUES (
                            @Timestamp,     @CloudCover,    @DewPoint,          @Humidity,  @Pressure,      @RainRate, 
                            @SkyBrightness, @SkyQuality,    @SkyTemperature,    @StarFwhm,  @Temperature,   @WindDirection, 
                            @WindGust,      @WindSpeed,     @IsSafeInt,         @Notes
                        )";

            // Execute INSERT using Dapper
            connection.Execute(sql, data);
        }

        /// <summary>
        /// Get data for a specific time range with optional aggregation
        /// </summary>
        /// <param name="startTime">Start of time range (inclusive)</param>
        /// <param name="endTime">End of time range (inclusive)</param>
        /// <param name="slotDuration">Duration of each time slot for aggregation (null for raw data)</param>
        /// <param name="aggregationFunction">Function to use for aggregation (only used if slotDuration is specified)</param>
        /// <returns>List of observing data (raw or aggregated) sorted by timestamp</returns>
        public List<ObservingData> GetData(
            DateTime startTime,
            DateTime endTime,
            TimeSpan? slotDuration = null,
            AggregationFunction aggregationFunction = AggregationFunction.Average) {
            if (endTime < startTime) {
                throw new ArgumentException("End time must be greater than or equal to start time");
            }

            if (slotDuration.HasValue && slotDuration.Value <= TimeSpan.Zero) {
                throw new ArgumentException("Slot duration must be positive");
            }

            // If no aggregation requested, return raw data
            if (!slotDuration.HasValue) {
                return GetRawData(startTime, endTime);
            }

            // Aggregate data using SQL
            return GetAggregatedData(startTime, endTime, slotDuration.Value, aggregationFunction);
        }

        /// <summary>
        /// Returns the latest record in reverse chronological order that is not newer than <paramref name="endTime"/>
        /// and not older than <paramref name="maxLookback"/>.
        /// </summary>
        public ObservingData? GetLatestData(DateTime endTime, TimeSpan maxLookback) {
            if (maxLookback <= TimeSpan.Zero) {
                throw new ArgumentException("Max lookback must be positive", nameof(maxLookback));
            }

            var startTime = endTime - maxLookback;
            var currentMonth = new DateTime(endTime.Year, endTime.Month, 1);
            var startMonth = new DateTime(startTime.Year, startTime.Month, 1);

            while (currentMonth >= startMonth) {
                var dbPath = GetDatabasePath(currentMonth);
                if (File.Exists(dbPath)) {
                    using var connection = new FbConnection(GetConnectionString(dbPath));
                    connection.Open();

                    const string sql = @"
                        SELECT
                            CREATED_AT      AS ""Timestamp"",
                            CLOUD_COVER     AS CloudCover,
                            DEW_POINT       AS DewPoint,
                            HUMIDITY        AS Humidity,
                            PRESSURE        AS Pressure,
                            RAIN_RATE       AS RainRate,
                            SKY_BRIGHTNESS  AS SkyBrightness,
                            SKY_QUALITY     AS SkyQuality,
                            SKY_TEMPERATURE AS SkyTemperature,
                            STAR_FWHM       AS StarFwhm,
                            TEMPERATURE     AS Temperature,
                            WIND_DIRECTION  AS WindDirection,
                            WIND_GUST       AS WindGust,
                            WIND_SPEED      AS WindSpeed,
                            IS_SAFE         AS IsSafeInt,
                            NOTES           AS Notes
                        FROM METEO_DATA
                        WHERE CREATED_AT >= @startTime AND CREATED_AT <= @endTime
                        ORDER BY CREATED_AT DESC
                        OFFSET 0 ROWS FETCH FIRST 1 ROWS ONLY";

                    var latest = connection.QueryFirstOrDefault<ObservingData>(sql, new { startTime, endTime });
                    if (latest != null) {
                        return latest;
                    }
                }

                currentMonth = currentMonth.AddMonths(-1);
            }

            return null;
        }

        #endregion Public Methods

        #region Private Methods

        /// <summary>
        /// Build query for First and Last aggregation functions
        /// </summary>
        /// <remarks>
        /// SlotSeconds is interpolated directly into SQL because Firebird does not allow
        /// parameters in GROUP BY/PARTITION BY expressions - they must be constants at prepare time.
        /// </remarks>
        private static string BuildFirstLastQuery(AggregationFunction function, long slotSeconds) {
            string orderDirection = function == AggregationFunction.First ? "ASC" : "DESC";

            // Use ROW_NUMBER to find first/last record in each slot by timestamp
            return $@"
                WITH RankedData AS (
                    SELECT 
                        *,
                        CAST(DATEDIFF(SECOND, TIMESTAMP '1970-01-01 00:00:00', CREATED_AT) / {slotSeconds} AS BIGINT) as TimeSlot,
                        ROW_NUMBER() OVER (
                            PARTITION BY CAST(DATEDIFF(SECOND, TIMESTAMP '1970-01-01 00:00:00', CREATED_AT) / {slotSeconds} AS BIGINT) 
                            ORDER BY CREATED_AT {orderDirection}
                        ) as RowNum
                    FROM METEO_DATA
                    WHERE CREATED_AT >= @StartTime AND CREATED_AT <= @EndTime
                )
                SELECT 
                    MIN(CREATED_AT) as ""Timestamp"",
                    MAX(CREATED_AT) as TimestampEnd,
                    COUNT(*) as RecordCount,
                    MAX(CASE WHEN RowNum = 1 THEN CLOUD_COVER END) as CloudCover,
                    MAX(CASE WHEN RowNum = 1 THEN DEW_POINT END) as DewPoint,
                    MAX(CASE WHEN RowNum = 1 THEN HUMIDITY END) as Humidity,
                    MAX(CASE WHEN RowNum = 1 THEN PRESSURE END) as Pressure,
                    MAX(CASE WHEN RowNum = 1 THEN RAIN_RATE END) as RainRate,
                    MAX(CASE WHEN RowNum = 1 THEN SKY_BRIGHTNESS END) as SkyBrightness,
                    MAX(CASE WHEN RowNum = 1 THEN SKY_QUALITY END) as SkyQuality,
                    MAX(CASE WHEN RowNum = 1 THEN SKY_TEMPERATURE END) as SkyTemperature,
                    MAX(CASE WHEN RowNum = 1 THEN STAR_FWHM END) as StarFwhm,
                    MAX(CASE WHEN RowNum = 1 THEN TEMPERATURE END) as Temperature,
                    MAX(CASE WHEN RowNum = 1 THEN WIND_DIRECTION END) as WindDirection,
                    MAX(CASE WHEN RowNum = 1 THEN WIND_GUST END) as WindGust,
                    MAX(CASE WHEN RowNum = 1 THEN WIND_SPEED END) as WindSpeed,
                    SUM(CASE WHEN IS_SAFE = 1 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(IS_SAFE), 0) as SafePercentage
                FROM RankedData
                GROUP BY TimeSlot
                ORDER BY ""Timestamp""
            ";
        }

        /// <summary>
        /// Build query for standard aggregation functions (AVG, MIN, MAX, SUM, COUNT)
        /// </summary>
        /// <remarks>
        /// SlotSeconds is interpolated directly into SQL because Firebird does not allow
        /// parameters in GROUP BY expressions - they must be constants at prepare time.
        /// </remarks>
        private static string BuildStandardAggregationQuery(AggregationFunction function, long slotSeconds) {
            string sqlFunc = function switch {
                AggregationFunction.Average => "AVG",
                AggregationFunction.Minimum => "MIN",
                AggregationFunction.Maximum => "MAX",
                AggregationFunction.Sum => "SUM",
                AggregationFunction.Count => "COUNT",
                _ => throw new ArgumentException($"Unknown aggregation function: {function}")
            };

            return $@"
                SELECT 
                    MIN(CREATED_AT) as ""Timestamp"",
                    MAX(CREATED_AT) as TimestampEnd,
                    COUNT(*) as RecordCount,
                    {sqlFunc}(CLOUD_COVER) as CloudCover,
                    {sqlFunc}(DEW_POINT) as DewPoint,
                    {sqlFunc}(HUMIDITY) as Humidity,
                    {sqlFunc}(PRESSURE) as Pressure,
                    {sqlFunc}(RAIN_RATE) as RainRate,
                    {sqlFunc}(SKY_BRIGHTNESS) as SkyBrightness,
                    {sqlFunc}(SKY_QUALITY) as SkyQuality,
                    {sqlFunc}(SKY_TEMPERATURE) as SkyTemperature,
                    {sqlFunc}(STAR_FWHM) as StarFwhm,
                    {sqlFunc}(TEMPERATURE) as Temperature,
                    {sqlFunc}(WIND_DIRECTION) as WindDirection,
                    {sqlFunc}(WIND_GUST) as WindGust,
                    {sqlFunc}(WIND_SPEED) as WindSpeed,
                    SUM(CASE WHEN IS_SAFE = 1 THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(IS_SAFE), 0) as SafePercentage
                FROM METEO_DATA
                WHERE CREATED_AT >= @StartTime AND CREATED_AT <= @EndTime
                GROUP BY CAST(DATEDIFF(SECOND, TIMESTAMP '1970-01-01 00:00:00', CREATED_AT) / {slotSeconds} AS BIGINT)
                ORDER BY ""Timestamp""
            ";
        }

        /// <summary>
        /// Create database and table if they don't exist
        /// </summary>
        private void EnsureDatabaseExists(string dbPath) {
            var directory = Path.GetDirectoryName(dbPath);
            if (!Directory.Exists(directory)) {
                Directory.CreateDirectory(directory!);
            }

            if (!File.Exists(dbPath)) {
                // Create database with FireBird 5 on localhost
                var csb = new FbConnectionStringBuilder {
                    DataSource = "localhost",
                    Database = dbPath,
                    UserID = _userName,
                    Password = _password,
                    ServerType = FbServerType.Default,
                    Charset = "UTF8",
                    WireCrypt = FbWireCrypt.Enabled,
                    Pooling = false
                };

                FbConnection.CreateDatabase(csb.ToString());

                // Create table with IDENTITY column (FireBird 5 auto-increment)
                using var connection = new FbConnection(GetConnectionString(dbPath));
                connection.Open();

                // Create table
                using (var command = connection.CreateCommand()) {
                    command.CommandText = @"CREATE TABLE METEO_DATA (
                        ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        CREATED_AT TIMESTAMP NOT NULL,
                        CLOUD_COVER DOUBLE PRECISION,
                        DEW_POINT DOUBLE PRECISION,
                        HUMIDITY DOUBLE PRECISION,
                        PRESSURE DOUBLE PRECISION,
                        RAIN_RATE DOUBLE PRECISION,
                        SKY_BRIGHTNESS DOUBLE PRECISION,
                        SKY_QUALITY DOUBLE PRECISION,
                        SKY_TEMPERATURE DOUBLE PRECISION,
                        STAR_FWHM DOUBLE PRECISION,
                        TEMPERATURE DOUBLE PRECISION,
                        WIND_DIRECTION DOUBLE PRECISION,
                        WIND_GUST DOUBLE PRECISION,
                        WIND_SPEED DOUBLE PRECISION,
                        IS_SAFE INTEGER,
                        NOTES VARCHAR(1000)
                        )";
                    command.ExecuteNonQuery();
                }

                // Create index
                using (var command = connection.CreateCommand()) {
                    command.CommandText = "CREATE INDEX IDX_CREATED_AT ON METEO_DATA(CREATED_AT)";
                    command.ExecuteNonQuery();
                }
            }
        }

        /// <summary>
        /// Get aggregated data using Dapper for better performance and type safety
        /// </summary>
        private List<ObservingData> GetAggregatedData(
            DateTime startTime,
            DateTime endTime,
            TimeSpan slotDuration,
            AggregationFunction aggregationFunction) {
            var results = new List<ObservingData>();
            var slotSeconds = (long)slotDuration.TotalSeconds;

            // Iterate through all months in the range
            var currentDate = new DateTime(startTime.Year, startTime.Month, 1);
            var endDate = new DateTime(endTime.Year, endTime.Month, 1);

            while (currentDate <= endDate) {
                var dbPath = GetDatabasePath(currentDate);

                if (File.Exists(dbPath)) {
                    using var connection = new FbConnection(GetConnectionString(dbPath));
                    connection.Open();

                    string query;

                    // For First and Last, we need a different query strategy
                    if (aggregationFunction == AggregationFunction.First ||
                        aggregationFunction == AggregationFunction.Last) {
                        query = BuildFirstLastQuery(aggregationFunction, slotSeconds);
                    } else {
                        query = BuildStandardAggregationQuery(aggregationFunction, slotSeconds);
                    }

                    // Execute query using Dapper - maps directly to ObservingData
                    // Note: SlotSeconds is interpolated directly into SQL, not passed as parameter
                    var aggregatedData = connection.Query<ObservingData>(
                        query,
                        new { StartTime = startTime, EndTime = endTime }
                    );

                    results.AddRange(aggregatedData);
                }

                currentDate = currentDate.AddMonths(1);
            }

            return [.. results.OrderBy(d => d.Timestamp)];
        }

        /// <summary>
        /// Get connection string for a database
        /// </summary>
        private string GetConnectionString(string dbPath) {
            var builder = new FbConnectionStringBuilder {
                DataSource = "localhost",
                Database = dbPath,
                UserID = _userName,
                Password = _password,
                ServerType = FbServerType.Default,
                Charset = "UTF8",
                WireCrypt = FbWireCrypt.Enabled
            };

            return builder.ToString();
        }

        /// <summary>
        /// Get database file path for a specific date
        /// </summary>
        private string GetDatabasePath(DateTime date) {
            var yearFolder = Path.Combine(_storageRootPath, date.Year.ToString());
            var dbFileName = $"{date:MM}{DatabaseFileExtension}";
            return Path.Combine(yearFolder, dbFileName);
        }
        /// <summary>
        /// Get raw data from database shards
        /// </summary>
        private List<ObservingData> GetRawData(DateTime startTime, DateTime endTime) {
            var results = new List<ObservingData>();

            // Iterate through all months in the range
            var currentDate = new DateTime(startTime.Year, startTime.Month, 1);
            var endDate = new DateTime(endTime.Year, endTime.Month, 1);

            while (currentDate <= endDate) {
                var dbPath = GetDatabasePath(currentDate);

                if (File.Exists(dbPath)) {
                    using var connection = new FbConnection(GetConnectionString(dbPath));
                    connection.Open();

                    const string sql = @"
                        SELECT 
                            CREATED_AT      AS ""Timestamp"", 
                            CLOUD_COVER     AS CloudCover, 
                            DEW_POINT       AS DewPoint, 
                            HUMIDITY        AS Humidity, 
                            PRESSURE        AS Pressure, 
                            RAIN_RATE       AS RainRate, 
                            SKY_BRIGHTNESS  AS SkyBrightness, 
                            SKY_QUALITY     AS SkyQuality, 
                            SKY_TEMPERATURE AS SkyTemperature, 
                            STAR_FWHM       AS StarFwhm, 
                            TEMPERATURE     AS Temperature, 
                            WIND_DIRECTION  AS WindDirection, 
                            WIND_GUST       AS WindGust, 
                            WIND_SPEED      AS WindSpeed, 
                            IS_SAFE         AS IsSafeInt, 
                            NOTES           AS Notes
                        FROM METEO_DATA 
                        WHERE CREATED_AT >= @startTime AND CREATED_AT <= @endTime
                        ORDER BY CREATED_AT ASC";

                    var data = connection
                        .Query<ObservingData>(sql, new { startTime, endTime })
                        .ToList();

                    results.AddRange(data);
                }

                currentDate = currentDate.AddMonths(1);
            }

            return [.. results.OrderBy(d => d.Timestamp)];
        }

        #endregion Private Methods
    }
}
